from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

# app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('gift_item/<int:wishlist_id>/<int:item_id>/', views.gift_item, name='gift_item'),
    path('register/', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('confirm_phone/<uidb64>/', views.confirm_phone, name='confirm_phone'),
    path('resend_pin/', views.resend_pin, name='resend_pin'),
    path('create_wishlist/', views.create_wishlist, name='create_wishlist'),
    path('edit_wishlist/<int:wishlist_id>/', views.edit_wishlist, name='edit_wishlist'),
    path('wishlists/', views.view_wishlists, name='wishlists'),
    path('wishlist/<int:wishlist_id>/', views.view_wishlist, name='view_wishlist'),
    path('wishlist/<int:wishlist_id>/add_store_item/<int:item_id>/', views.add_store_item_to_wishlist,
         name='add_store_item_to_wishlist'),
    path('wishlist/<int:wishlist_id>/add_custom_item/', views.add_custom_item_to_wishlist,
         name='add_custom_item_to_wishlist'),
    path('wishlist/<int:wishlist_id>/add_item/', views.add_item_to_wishlist, name='add_item_to_wishlist'),
    path('reset_password_request/', views.CustomPasswordResetView.as_view(), name='reset_password_request'),
    path('reset_password_request/', views.CustomPasswordResetView.as_view(), name='reset_password_request'),
    path('reset_password_done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
    path('resend_pin/', views.resend_pin, name='resend_pin'),
    path('profile/', views.edit_profile, name='profile'),
    path('add_item_to_wishlist/', views.add_item_to_wishlist, name='add_item_to_wishlist'),
    path('all_wishlists', views.all_wishlists, name='all_wishlists'),
    path('wishlist/<int:wishlist_id>/update-expiry-date/', views.update_expiry_date, name='update_expiry_date'),
    path('remove_item/<int:item_id>/', views.remove_item_from_wishlist, name='remove_item_from_wishlist'),
    path('edit_custom_item/<int:item_id>/', views.edit_custom_item, name='edit_custom_item'),
    path('pay_for_item/<int:item_id>/', views.pay_for_item, name='pay_for_item'),
    path('wishlist/<int:wishlist_id>/transfer_extra_cash/', views.transfer_extra_cash, name='transfer_extra_cash'),
    path('wishlist/<int:wishlist_id>/allocate_extra_cash/', views.allocate_extra_cash, name='allocate_extra_cash'),
]
