# Generated by Django 5.0.7 on 2024-08-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Refurbished', 'Refurbished')], default='New', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='popularity_count',
            field=models.IntegerField(default=0),
        ),
    ]
