# Generated by Django 5.0.7 on 2024-08-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_vendor_groups_vendor_is_active_vendor_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
