# Generated by Django 5.0.7 on 2024-08-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/items/'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='item_image_url',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
